version: '3.8'
services:
  gateway:
    build: gateway/
    container_name: shareit_gateway
    ports:
      - "8080:8080"
    depends_on: [ server ]
    environment:
      SHAREIT_SERVER_URL: http://server:8085

  server:
    build: service/
    container_name: shareit_server
    ports:
      - "8085:8085"
    depends_on: [ db ]
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13.7-alpine
    container_name: shareit_db
    ports:
      - "6541:5432"

    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root